### ISSUE TITLE
images

### ISSUE THREAD

**Issue by guanchenY** [jovans2/MXFaaS_Artifact#10]
Can you tell me how the jovanvr97/cnn_serve_start image is created, such as its Dockerfile and code file? I am looking forward to your reply and thank you very much.

**Comment by Nyovelt** [comment]
It can be found at [KNative_prototype/cnn_serving](https://github.com/jovans2/MXFaaS_Artifact/tree/main/KNative_prototype/cnn_serving)

**Comment by Nyovelt** [comment]
I think it is almost the same as `python:3.8-slim`.

**Comment by guanchenY** [comment]
Not&nbsp;jovanvr97/cnn_serving_knative, I want to know how to build cnn_serve_start. Thank you very much if you tell me!



---Original---
From: ***@***.***&gt;
Date: Sun, Dec 17, 2023 01:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jovans2/MXFaaS_Artifact] images (Issue #10)




 
It can be found at KNative_prototype/cnn_serving

**Comment by guanchenY** [comment]
Thank you very much! Because I don't use Azure Blob Storage in China,so I want to know it. Good luck for you every day!



---Original---
From: ***@***.***&gt;
Date: Sun, Dec 17, 2023 01:31 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jovans2/MXFaaS_Artifact] images (Issue #10)




 
I think it is almost the same as python:3.8-slim.

**Comment by tianyin** [comment]
@Nyovelt you are awesome!
