### ISSUE TITLE
Evaluation rate setting?

### ISSUE THREAD

**Issue by HigashikataZhangsuke** [jovans2/MXFaaS_Artifact#13]
Hi Jovan,

In the oringinal paper, it mentioned that: "Workloads. We evaluate MXFaaS under low, medium, and high load levels, corresponding to an average of 450 requests per second (RPS), 1000 RPS, and 1800 RPS, respectively. " However in the code the load level is 5,30 and 80 for poission arrivals. How do these RPS aligns the numbers in paper?

In addition, how can we get the real CPU resource usage? The current logger usually records the function allocation of all CPUs, regardless of whether they are actually used. But when there are fewer requests, sometimes MXFaaS will not use all CPUs to process requests. In this case, how can we get the real CPU usage?

And the last question is about Multiple VM tests. Firstly we need to change the MaxVM paramemter in nodeController.py, but what steps should we take after that? The original test only used minikube, which looks like a single node setting.

Best,
Yinzhe

**Comment by jovans2** [comment]
Hi Yinzhe,

The numbers used in the artifact are meant for small scale testing (such as 1-node with Knative and minikube). For the evaluation in the paper, we used OpenWhisk on 15-server cluster where each server is an AMD Epyc with 24 cores. 

We measured CPU utilization using “docker stats” command. 

Let me know if I can help further.

**Comment by HigashikataZhangsuke** [comment]
Thanks for answering those questions! So, only the OpenWhisk setting supports multiplenode test, right? Or the KN setting also supports, but I need to figure out how to do that?

Besides, how does the performance of KN and Openwhisk settings differed? Or they are the same basically? If possible could I get a copy of the OpenWhisk version of MXfaaS?

**Comment by jovans2** [comment]
You could use KNative in multi-node environment as well. However, it is not included in this artifact. For that, you’d need to follow the instructions from KNative official page. We will probably open-source the OpenWhisk version as well, however, I am not sure when.
