### ISSUE TITLE
Lack of sending request to port 5500

### ISSUE THREAD

**Issue by GitHubDiom** [jovans2/MXFaaS_Artifact#2]
Hi, there,
I notice that runner.py for each function in KNative_prototype acts like an OpenWhisk actionloop. 
The updateThread function listened on port 5500 but did not find the part that sent the socket request to port 5050.
May I ask where the socket request for port 5500 is sent?

Thank you

**Comment by jovans2** [comment]
Hello,

As you noticed, the code was primarily designed for OpenWhisk and later adjusted to work with KNative. In OpenWhisk, functions are deployed as Docker containers and our nodeController is able to get the IP address of each function individually. Then, the nodeController sends the updateCoreNum messages to the function directly on port 5500. With KNative, it is not easy to get the IP address of a given container, thus, the nodeController uses the function's proxy address obtained via "kn service list". Therefore, the updateThread functionality is incorporated in the main body of the runner.py (lines 454-462). The code for updateThread is left to be compatible with OpenWhisk and our nodeController version for OpenWhisk.

Hopefully, this answers your question, Let us know if you have any further questions/comments/concerns!

Jovan
