### ISSUE TITLE
where is MXContainer？

### ISSUE THREAD

**Issue by casun18** [jovans2/MXFaaS_Artifact#6]
Recently I was trying to reproduce your paper, and I saw that it mentioned using the `MXContainer` module to achieve resource sharing.
Can you explain what parts of the code correspond to `MXContaine`r?

**Comment by casun18** [comment]
Additionally, when I ran `knative_all.py`, I encountered the following error
```shell
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7f79a06b3670>: Failed to resolve 'cnn-serving.default.svc.cluster.local' ([Errno -3] Temporary failure in name resolution)
```
It seems that `lambda_func(service)` is not executing at the correct address

**Comment by jovans2** [comment]
Hello, the main file of an MXContainer is the `runner.py` file in every function subfolder within the `KNative_prototype`, e.g., `https://github.com/jovans2/MXFaaS_Artifact/blob/main/KNative_prototype/cnn_serving/runner.py`. In the code, the Dispatcher is the main process, it waits on user requests and forks a Handler when an invocation arrives. Let me know if you need more details about the code.

Regarding the issue you encountered -- can you give us more insights on what environment you're testing on and how to reproduce the error? Have you setup the system using our initialization scripts? Can you check that all KNative services are up and running?

**Comment by casun18** [comment]
Thanks for your reply, I just didn't start `minikube tunnel.`
