### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by guanchenY** [jovans2/MXFaaS_Artifact#8]
I would like to know what command is used when you create an image through Dockerfile, can you tell me?

**Comment by jovans2** [comment]
Hello, we used a standard way to build Docker images --- `docker build -t IMAGE_NAME .` 
You should be positioned in the folder of your function with the Dockerfile (e.g., https://github.com/jovans2/MXFaaS_Artifact/blob/main/KNative_prototype/img_rot/Dockerfile).

Let me know if you have any issues with it.
