### ISSUE TITLE
The minimum configuration for experimental reproduction

### ISSUE THREAD

**Issue by liuzeyu-sudo** [jovans2/MXFaaS_Artifact#9]
Hello, I would like to reproduce the experiment in the paper. What is the minimum configuration? Can you please tell me? Thank you very much

**Comment by jovans2** [comment]
Hello, can you clarify what you mean by "minimum configuration"? You can check "Artifact Appendix" in our paper which shows how to use the artifact in order to reproduce paper results. It also specifies what are the requirements (both hardware and software).

**Comment by liuzeyu-sudo** [comment]
![image](https://github.com/jovans2/MXFaaS_Artifact/assets/59641650/e29356cf-e9c1-4d95-a08e-827ca24f6fe0)

Cannot install Knative serving
I encountered a problem following your tutorial. Could you please let me know what the problem is?

**Comment by jovans2** [comment]
Hi, Thanks for sharing. Most likely, you run out of disk/memory space. Can you please check how much space is left on your device and if needed to repartition your file system to add more storage capacity to the partition where you installed and run the artifact?

**Comment by Nyovelt** [comment]
Given the `ImagePullBackOff` status, can you access the Docker registry without any issues?
